module.exports = [

  // common fields
  '_root_',
  'type_s',
  'id',
  'owner_id',
  'client_name',
  'eng_mgr_name',
  'created_on',
  'updated_on',

  // Jobs Fields
  'role',
  'perks',
  'responsibility',
  'comments',
  'job_nature',
  'days_per_week',
  'start_work_time',
  'end_work_time',
  'interview_addr',
  'interview_place_direction',
  'preferred_genders',
  'direct_line_up',
  'recruiter_username',
  'email',
  'min_sal',
  'max_sal',
  'min_exp',
  'max_exp',
  'vacancy',
  'job_content',
  'job_status',
  'job_code',
  'job_location',
  'functional_area',
  'required_skills',
  'optional_skills',

  // Applicants Fields
  'name',
  'state_id',
  'state_name',
  'client_score',
  'consultant_score',
  'screening_score',
  'total_exp',
  'expected_ctc',
  'notice_period',
  'applicant_score',
  'latest_comment',
  'resume',
  'consultant_username',
  'mobile',
  'interview_time',
  'interview_type',
  'verified',
  'edu_institute',
  'edu_degree',
  'edu_location',
  'edu_start',
  'edu_end',
  'exp_employer',
  'exp_designation',
  'exp_location',
  'exp_salary',
  'exp_start',
  'exp_end',
  'skills',
  'degrees',
  'employers',
  'industries',
  'institutes',
];
